// plugins/_templates/vue_plugin/src/App.vue
<!-- 可选 SFC 源码（§16 审核要求：提交打包产物必须附源码 + 可复现构建）
     构建命令（esbuild，项目已有该依赖）：
       npx esbuild src/App.vue --bundle --format=iife --outfile=static/js/app.js --loader:.vue=jsx
     构建后 app.js 会引用系统 UMD 全局 Vue，保持挂载点 #app 不变。 -->
<template>
  <div class="vd-card">
    <h2>{{ title }}</h2>
    <p>{{ desc }}</p>
    <p class="vd-muted">{{ tokenLabel }}: <b>{{ tokenStatus }}</b></p>
    <button @click="callApi">{{ callLabel }}</button>
    <p id="vd-result" class="vd-muted"></p>
  </div>
</template>

<script>
export default {
  name: 'VueDemoApp',
  data() {
    const T = window.__t || {};
    const TOKEN = window.__SSO_TOKEN || '';
    return {
      title: T['demo.title'] || 'Vue Plugin Demo',
      desc: T['demo.desc'] || 'This page is rendered by Vue 3 (local UMD, no CDN).',
      tokenLabel: T['demo.token'] || 'SSO token',
      callLabel: T['demo.call'] || 'Call API',
      tokenStatus: TOKEN ? 'ok' : 'missing'
    };
  },
  methods: {
    callApi() {
      const TOKEN = window.__SSO_TOKEN || '';
      fetch('/admin/vue-demo/api/hello', {
        headers: { Authorization: 'Bearer ' + TOKEN }
      })
        .then((r) => r.json())
        .then((d) => { document.getElementById('vd-result').textContent = JSON.stringify(d); })
        .catch((e) => console.error(e));
    }
  }
};
</script>

// plugins/_templates/react_plugin/static/js/app.js
/* React Demo — 无构建入口（React UMD + React.createElement，纯静态文件）
 * 系统本地 React 库由 index.html 注入，此文件只依赖 window.__SSO_TOKEN / window.__t。
 * 如需 JSX：见 src/App.jsx + 构建命令（esbuild 产物输出到本文件位置）。
 */
(function () {
  var TOKEN = window.__SSO_TOKEN || '';
  var T = window.__t || {};

  function DemoApp() {
    return React.createElement(
      'div',
      { className: 'rd-card' },
      React.createElement('h2', null, T['demo.title'] || 'React Plugin Demo'),
      React.createElement('p', null, T['demo.desc'] || 'This page is rendered by React 18 (local UMD, no CDN).'),
      React.createElement('p', { className: 'rd-muted' },
        (T['demo.token'] || 'SSO token') + ': ' + (TOKEN ? 'ok' : 'missing')),
      React.createElement('button', { onClick: callApi }, T['demo.call'] || 'Call API'),
      React.createElement('p', { id: 'rd-result', className: 'rd-muted' })
    );
  }

  function callApi() {
    // 同域 API，携带 Bearer token（§15.4：禁止发往第三方域名）
    fetch('/admin/react-demo/api/hello', {
      headers: { Authorization: 'Bearer ' + TOKEN }
    })
      .then(function (r) { return r.json(); })
      .then(function (d) {
        document.getElementById('rd-result').textContent = JSON.stringify(d);
      })
      .catch(function (e) { console.error(e); });
  }

  var root = document.getElementById('app');
  if (root) {
    ReactDOM.createRoot(root).render(React.createElement(DemoApp, null));
  }
})();
